apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-pvc
  labels:
        app: nginx-pvc
spec:
    containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
          - name: pvc-mount
            mountPath: /usr/share/nginx/html
    volumes:
        - name: pvc-mount
          persistentVolumeClaim:
             claimName: obs-provision-pvc

--- 
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx-pvc
  ports:
  -  protocol: TCP
     port: 80
     targetPort: 80
  type: NodePort
