apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: configmap-container
      image: busybox
      command: 
         - sleep 
         - "3600"
      envFrom:
      - configMapRef:
          name: mysqldb-env-config
  
